filter:
    excluded_paths:
        - "tests/"
        - "resources/"
        - "vendor/"
        - "src/CssMin/"
        - "src/JsMin/"
checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 1

build:
    environment:
        php: 7.1.1
        mysql: true
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'